apiVersion: apps/v1
kind: Deployment
metadata:
  name: xydjygzh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xydjygzh
  template:
    metadata:
      labels:
        app: xydjygzh
    spec:
      containers:
      - image: okteto.dev/xydjygzh:latest
        name: xydjygzh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "31a9d4a0-46cb-42b1-91a6-03837f04de3c"
        - name: Vless_Path
          value: "/kmsdlw"
        - name: Vmess_UUID
          value: "31a9d4a0-46cb-42b1-91a6-03837f04de3c"
        - name: Vmess_Path
          value: "/xhdjzh"
        - name: Share_Path
          value: "/gxsddl"
